import { strict as assert } from 'node:assert'
import { defineTestSuite } from '../src'
import { describe, it } from 'vitest'

const testSuite = defineTestSuite({
  '.events': true,
  '._get': true,
  '._find': true,
  '._create': true,
  '._update': true,
  '._patch': true,
  '._remove': true,
  '.$get': true,
  '.$find': true,
  '.$create': true,
  '.$update': true,
  '.$patch': true,
  '.$remove': true,
  '.get': true,
  '.get + $select': true,
  '.get + id + query': true,
  '.get + NotFound': true,
  '.find': true,
  '.remove': true,
  '.remove + $select': true,
  '.remove + id + query': true,
  '.remove + multi': true,
  '.remove + multi no pagination': true,
  '.update': true,
  '.update + $select': true,
  '.update + id + query': true,
  '.update + NotFound': true,
  '.patch': true,
  '.patch + $select': true,
  '.patch + id + query': true,
  '.patch multiple': true,
  '.patch multiple no pagination': true,
  '.patch multi query changed': true,
  '.patch multi query same': true,
  '.patch + NotFound': true,
  '.create': true,
  '.create + $select': true,
  '.create multi': true,
  'internal .find': true,
  'internal .get': true,
  'internal .create': true,
  'internal .update': true,
  'internal .patch': true,
  'internal .remove': true,
  '.find + equal': true,
  '.find + equal multiple': true,
  '.find + $sort': true,
  '.find + $sort + string': true,
  '.find + $limit': true,
  '.find + $limit 0': true,
  '.find + $skip': true,
  '.find + $select': true,
  '.find + $or': true,
  '.find + $in': true,
  '.find + $nin': true,
  '.find + $lt': true,
  '.find + $lte': true,
  '.find + $gt': true,
  '.find + $gte': true,
  '.find + $ne': true,
  '.find + $gt + $lt + $sort': true,
  '.find + $or nested + $sort': true,
  '.find + paginate': true,
  '.find + paginate + $limit + $skip': true,
  '.find + paginate + $limit 0': true,
  '.find + paginate + params': true,
  '.get + id + query id': true,
  '.remove + id + query id': true,
  '.update + id + query id': true,
  '.patch + id + query id': true,
  '.create ignores query': false,
  '.find + $and + $or': false,
  '.find + $and': false,
  '.find + paginate + query': false,
  '.id': false,
  '.options': false,
  '.patch + query + NotFound': false,
  '.update + query + NotFound': false,
  'params.adapter + multi': false,
  'params.adapter + paginate': false,
})

describe('Feathers Memory Service', () => {
  it('loads the test suite', () => {
    assert.ok(typeof testSuite === 'function')
  })
})
